DancingGoat/Models/ContentTypes/AboutUs.cs
namespace DancingGoat.Models
{
    public partial class AboutUs : IMetadata
    {
    }
}

DancingGoat/Models/ContentTypes/Article.cs
namespace DancingGoat.Models
{
    public partial class Article : IMetadata, IDetailItem
    {
        public string Type => System.Type;
        public string Id => System.Id;
    }
}

DancingGoat/Models/ContentTypes/Cafe.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace DancingGoat.Models
{
    [ModelMetadataType(typeof(CafeMetadata))]
    public partial class Cafe
    {
    }

    public class CafeMetadata
    {
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [EmailAddress]
        public string Email { get; set; }
    }
}

DancingGoat/Models/ContentTypes/FactAboutUs.cs
namespace DancingGoat.Models
{
    public partial class FactAboutUs
    {
    }
}

DancingGoat/Models/ContentTypes/HostedVideo.cs
namespace DancingGoat.Models
{
    public partial class HostedVideo
    {
    }
}

DancingGoat/Models/ViewModels/AboutUsViewModel.cs
using System.Collections.Generic;

namespace DancingGoat.Models
{
    public class AboutUsViewModel : AboutUs
    {
        public string ItemId { get; set; }
        public string Language { get; set; }
        public IList<FactAboutUsViewModel> FactViewModels { get; set; }
    }
}

DancingGoat/Models/ViewModels/CafesViewModel.cs
using System.Collections.Generic;

namespace DancingGoat.Models
{
    public class CafesViewModel
    {
        public List<Cafe> CompanyCafes { get; set; }

        public List<Cafe> PartnerCafes { get; set; }
    }
}

DancingGoat/Models/ViewModels/FactAboutUsViewModel.cs
using Kontent.Ai.Management.Helpers.Models;

namespace DancingGoat.Models
{
    public class FactAboutUsViewModel
    {
        public FactAboutUs Fact { get; set; }
        public bool Odd { get; set; }
        public ElementIdentifier ParentItemElementIdentifier { get; set; }
    }
}

DancingGoat/Controllers/ArticlesController.cs
using System;
using System.Globalization;
using System.Threading.Tasks;
using DancingGoat.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Kontent.Ai.Delivery.Abstractions;
using Kontent.Ai.Urls.Delivery.QueryParameters;
using Kontent.Ai.Urls.Delivery.QueryParameters.Filters;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Localization;
using Microsoft.Extensions.Localization;

namespace DancingGoat.Controllers
{
    public class ArticlesController : ControllerBase
    {
        private readonly IConfiguration _configuration;

        public ArticlesController(IConfiguration configuration, IDeliveryClientFactory deliveryClientFactory) : base(deliveryClientFactory)
        {
            _configuration = configuration;
        }
        
        public async Task<ActionResult> Index()
        {
            var response = await _client.GetItemsAsync<Article>(
                new OrderParameter("elements.post_date", SortOrder.Descending),
                new ElementsParameter(Article.TeaserImageCodename, Article.PostDateCodename, Article.SummaryCodename, Article.UrlPatternCodename, Article.TitleCodename),
                new LanguageParameter(Language)
            );

            return View(response.Items);
        }
        
        public async Task<ActionResult> Show(string urlSlug)
        {
            var response = await _client.GetItemsAsync<Article>(
                new EqualsFilter($"elements.{Article.UrlPatternCodename}", urlSlug),
                new DepthParameter(1),
                new LanguageParameter(Language)
            );

            if (response.Items[0].System.Language != Language)
            {
                var urlParts = Request.GetDisplayUrl().Split('/');
                urlParts[3] = response.Items[0].System.Language;
                var newUrl = String.Join('/', urlParts);
            
                return Redirect(newUrl);
            }

            if (response.Items.Count == 0)
            {
                return NotFound();
            }
            else
            {
                return View(response.Items[0]);
            }
        }
    }
}

DancingGoat/Controllers/CafesController.cs
using System.Linq;
using System.Threading.Tasks;
using DancingGoat.Models;
using DancingGoat.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace DancingGoat.Controllers
{
    public class CafesController : ControllerBase
    {
        public ICafesRepository CafesRepository { get; }

        public CafesController(ICafesRepository cafesRepository) : base()
        {
            CafesRepository = cafesRepository;
        }
        
        public async Task<ActionResult> Index()
        {
            var cafes = await CafesRepository.GetCafes(Language);

            var viewModel = new CafesViewModel
            {
                CompanyCafes = cafes.Where(c => c.Country == "USA").ToList(),
                PartnerCafes = cafes.Where(c => c.Country != "USA").ToList()
            };

            return View(viewModel);
        }
    }
}

DancingGoat/Controllers/ProductController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Kontent.Ai.Delivery.Abstractions;
using DancingGoat.Models;
using DancingGoat.Configuration;
using Kontent.Ai.Urls.Delivery.QueryParameters.Filters;
using Kontent.Ai.Urls.Delivery.QueryParameters;

namespace DancingGoat.Controllers
{

    public class ProductController : ControllerBase
    {
        public ProductController(IDeliveryClientFactory deliveryClientFactory) : base(deliveryClientFactory)
        {
        }
        
        public async Task<ActionResult> Detail(string urlSlug)
        {
            var item = (await _client.GetItemsAsync<object>(new EqualsFilter("elements.url_pattern", urlSlug), new InFilter("system.type", Brewer.Codename, Coffee.Codename), new LanguageParameter(Language))).Items.FirstOrDefault();

            if (item == null)
            {
                return NotFound();
            }
            else
            {
                ViewBag.FreeTasteRequested = TempData["formSubmited"] ?? false;
                ViewBag.UrlSlug = urlSlug;
                return View(item.GetType().Name, item);
            }
        }

        /// <summary>
        /// Dummy action.
        /// </summary>
        [HttpPost]
        public ActionResult FreeTaste()
        {
            // If needed, put your code here to work with the uploaded data in MVC.
            TempData["formSubmited"] = true;
            return RedirectToAction("Detail", new { urlSlug = Request.Form["product_url_slug"] });
        }
    }
}

DancingGoat/Views/Shared/DisplayTemplates/AboutUsViewModel.cshtml
@model DancingGoat.Models.AboutUsViewModel

@Html.DisplayFor(vm => vm.FactViewModels)

DancingGoat/Views/Shared/DisplayTemplates/Article.cshtml
@model DancingGoat.Models.Article

<div class="col-md-3">
    <div class="article-tile">
        <a asp-controller="Articles" asp-action="Show" asp-route-urlSlug="@Model.UrlPattern">
            <img-asset asset="@Model.TeaserImage.First()" class="article-tile-image" default-width="300" title="Article @Model.Title">
                <media-condition min-width="330" max-width="768" image-width="468" />
            </img-asset>
        </a>
        <div class="article-tile-date">
            @Model.PostDate?.ToString("M")
        </div>
        <div class="article-tile-content">
            <h2 class="h4">
                <a asp-controller="Articles" asp-action="Show" asp-route-urlSlug="@Model.UrlPattern">@Model.Title</a>
            </h2>
            <p class="article-tile-text">
                @Html.DisplayFor(vm => vm.Summary)
            </p>
        </div>
    </div>
</div>

DancingGoat/Views/Shared/DisplayTemplates/Cafe.cshtml
@model DancingGoat.Models.Cafe

<div class="col-md-6">
    <div class="cafe-tile cursor-hand js-scroll-to-map" data-address="@Model.City, @Model.Street">
        @if (ViewData.ContainsKey("ShowImage") && (bool)ViewData["ShowImage"] == true)
        {
            var photo = Model.Photo.FirstOrDefault();
            <div class="cafe-image-tile-image-wrapper" style="background-image:url('@(photo != null ? photo.Url: "")'); background-size: cover; background-position: right center;"></div>
        }
        <div class="cafe-tile-content">
            <h3 class="cafe-tile-name">@Html.DisplayFor(vm => vm.System.Name)</h3>
            <address class="cafe-tile-address">
                <a href="javascript:void(0)" class="cafe-tile-address-anchor">@Html.DisplayFor(vm => vm.Street), @Html.DisplayFor(vm => vm.City)<br />@Html.DisplayFor(vm => vm.ZipCode), @Html.DisplayFor(vm => vm.Country), @Html.DisplayFor(vm => vm.State)</a>
            </address>
            <p class="cafe-tile-phone">@Html.DisplayFor(vm => vm.Phone)</p>
        </div>
    </div>
</div>

DancingGoat/Views/Shared/DisplayTemplates/DateTime.cshtml
@model DateTime?

@{
    string keyName = nameof(DancingGoat.Helpers.Extensions.DateTimeFormatterParameters.FormatCharacter);

    if (ViewData.ContainsKey(keyName) && !string.IsNullOrEmpty(ViewData[keyName].ToString()) && Model.HasValue)
    {
        Output.Write(Model.Value.ToString(ViewData[keyName].ToString()));
    }
    else
    {
        @ViewData.TemplateInfo.FormattedModelValue
    }
}

DancingGoat/Views/Shared/DisplayTemplates/FactAboutUsViewModel.cshtml
@using DancingGoat.Models
@using Kontent.Ai.Management.Helpers.Models
@model DancingGoat.Models.FactAboutUsViewModel

<section class="row text-and-image">
    <h2 class="col-lg-12">
        @Model.Fact.Title
        <edit-link language="@Model.Fact.System.Language" inline="true" element-ids="@new ElementIdentifier[] {Model.ParentItemElementIdentifier, new ElementIdentifier(Model.Fact.System.Id, FactAboutUs.TitleCodename) }" />
    </h2>
    <div class="col-md-6@( Model.Odd ? " col-md-push-6" : "" )">
        <div class="text-and-image-text@(Model.Odd ? "-right" : "" )">
            @Html.DisplayFor(vm => vm.Fact.Description)
            <edit-link language="@Model.Fact.System.Language" inline="false" element-ids="@new ElementIdentifier[] {Model.ParentItemElementIdentifier, new ElementIdentifier(Model.Fact.System.Id, FactAboutUs.DescriptionCodename) }" />
        </div>
    </div>
    <div class="col-md-6@( Model.Odd ? " col-md-pull-6" : "" )">
        <img-asset asset="@Model.Fact.Image.First()" class="img-responsive" default-width="300">
            <media-condition min-width="1120" image-width="540" />
            <media-condition min-width="768" max-width="1120" image-width="370" />
            <media-condition min-width="330" max-width="768" image-width="468" />
        </img-asset>
        <edit-link language="@Model.Fact.System.Language" inline="false" element-ids="@new ElementIdentifier[] {Model.ParentItemElementIdentifier, new ElementIdentifier(Model.Fact.System.Id, FactAboutUs.ImageCodename) }" />
    </div>
</section>

DancingGoat/Views/Shared/DisplayTemplates/HostedVideo.cshtml
@model DancingGoat.Models.HostedVideo

@{ 
    var host = Model.VideoHost.FirstOrDefault()?.Codename;
    if (host == "vimeo") {
        <iframe class="hosted-video__wrapper"
                src="https://player.vimeo.com/video/@(Model.VideoId)?title =0&byline =0&portrait =0"
                width="640"
                height="360"
                frameborder="0"
                webkitallowfullscreen
                mozallowfullscreen
                allowfullscreen
                >
        </iframe>
    }
    else if (host == "youtube") {
        <iframe class="hosted-video__wrapper"
                width="560"
                height="315"
                src="https://www.youtube.com/embed/@(Model.VideoId)"
                frameborder="0"
                allowfullscreen
                >
        </iframe>
    }
}

DancingGoat/Views/Shared/DisplayTemplates/PhoneNumber.cshtml
@model string

@{
    string strippedDashes = string.IsNullOrWhiteSpace(Model) ? string.Empty : Model.Replace("-", string.Empty);
}

<a href="tel:@strippedDashes">@Model</a>

DancingGoat/Views/Shared/DisplayTemplates/Product.cshtml
@model DancingGoat.Models.IProduct
@{
    var price = Model.ProductPrice.HasValue ? Model.ProductPrice.Value.ToString("C") : "Price hasn't been set yet.";
}

<article class="product-tile">
    <a asp-controller="Product" asp-action="Detail" asp-route-urlSlug="@Model.ProductUrlPattern">
        <h1 class="product-heading">@Model.ProductProductName</h1>
        @if (Model.ProductProductStatus.Any())
        {
            <span class="product-tile-status">
                @Html.DisplayFor(vm => vm.ProductProductStatus.First().Name)
            </span>
        }
        <figure class="product-tile-image">
            <img-asset asset="@Model.ProductImage.First()" class="img-responsive" width="452" height="452" />
        </figure>
        <div class="product-tile-info">
            <span class="product-tile-price">
                @Html.DisplayFor(vm => price)
            </span>
        </div>
    </a>
</article>

DancingGoat/Views/Shared/DisplayTemplates/RelatedArticle.cshtml
@model DancingGoat.Models.Article

<div class="col-lg-3 col-md-6 col-sm-12">
    <div class="article-tile">
        <a asp-controller="Articles" asp-action="Show" asp-route-urlSlug="@Model.UrlPattern">
            <img-asset asset="@Model.TeaserImage.First()" class="article-tile-image" title="Article @Model.Title" />
        </a>
        <div class="article-tile-date">
            @Html.DateTimeFormattedFor(vm => vm.PostDate, "M")
        </div>
        <div class="article-tile-content">
            <h2 class="h4">
                <a asp-controller="Articles" asp-action="Show" asp-route-urlSlug="@Model.UrlPattern">@Html.DisplayFor(vm => vm.Title)</a>
            </h2>
            <p class="article-tile-text">
                @Html.DisplayFor(vm => vm.Summary)
            </p>
        </div>
    </div>
</div>